name: authmiddleware
description: "Fully managed Auth Middleware"
version: 1.0.1
homepage: https://github.com/launchlense-ai/authmiddleware-flutter

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: '>=1.1.0'
  flutter_secure_storage: '>=9.2.2 <10.0.0'
  fluttertoast: ^8.0.9
  logging: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
